import Accordion from 'react-bootstrap/Accordion';
import { Row, Col, Container, Button } from "react-bootstrap";
const Privacy = () => {

    return (
        <Container className="py-5">
            <h1>Privacy Policy</h1>
            <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>

            <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
            <Accordion>
                <Accordion.Item eventKey="0">
                    <Accordion.Header>Interpretation and Definitions</Accordion.Header>
                    <Accordion.Body>
                        <h2>Interpretation</h2>
                        <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

                        <h2>Definitions</h2>
                        <p>For the purposes of this Privacy Policy:</p>

                        <h3>Account</h3> <p>means a unique account created for You to access our Service or parts of our Service.</p>

                        <h3>Affiliate</h3> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.

                        <h3>Application</h3> means the software program provided by the Company downloaded by You on any electronic device, named e-tadweer

                        <h3>Company</h3> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to E-tadweer Masir, 6 Shawarbi Cairo Egypt .

                        <h3>Country</h3> refers to: Egypt

                        <h3>Device</h3> means any device that can access the Service such as a computer, a cellphone or a digital tablet.

                        <h3>Personal Data</h3> is any information that relates to an identified or identifiable individual.

                        <h3>Service</h3> refers to the Application.

                        <h3>Service Provider</h3> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.

                        <h3>Third-party Social Media Service</h3> refers to any website or any social network website through which a User can log in or create an account to use the Service.

                        <h3>Usage Data</h3> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).

                        <h3>You</h3> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.



                    </Accordion.Body>
                </Accordion.Item>
                <Accordion.Item eventKey="1">
                    <Accordion.Header>Collecting and Using Your Personal Data</Accordion.Header>
                    <Accordion.Body>
                        <h2>Types of Data Collected</h2>
                        <h2>Use of Your Personal Data</h2>
                        <p>The Company may use Personal Data for the following purposes:</p>

                        <p>To provide and maintain our Service, including to monitor the usage of our Service.</p>

                        <p>To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</p>

                        <p>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</p>

                        <p>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</p>

                        <p>To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</p>

                        <p>To manage Your requests: To attend and manage Your requests to Us.</p>

                        <p>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</p>

                        <p>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</p>

                        <p>We may share Your personal information in the following situations:</p>

                        <p>With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</p>
                        <p>For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</p>
                        <p>With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</p>
                        <p>With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.</p>
                        <p>With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.</p>
                        <p>With Your consent: We may disclose Your personal information for any other purpose with Your consent.</p>
                        <h2>Retention of Your Personal Data</h2>
                        <p> The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>

                        <p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>

                        <p>For your personal data deletion request please contact us</p>
                        <h2>Transfer of Your Personal Data</h2>
                        <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.

                            Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.

                            The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
                        <h2>Disclosure of Your Personal Data</h2>
                        <h2>Security of Your Personal Data</h2>

                    </Accordion.Body>
                </Accordion.Item>

                <Accordion.Item eventKey="2">
                    <Accordion.Header>Children's Privacy</Accordion.Header>
                    <Accordion.Body>
                        <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.

                            If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
                    </Accordion.Body>
                </Accordion.Item>

                <Accordion.Item eventKey="3">
                    <Accordion.Header>Links to Other Websites</Accordion.Header>
                    <Accordion.Body>
                        Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.

                        We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
                    </Accordion.Body>
                </Accordion.Item>

                <Accordion.Item eventKey="4">
                    <Accordion.Header>Changes to this Privacy Policy</Accordion.Header>
                    <Accordion.Body>
                        We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.

                        We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.

                        You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                    </Accordion.Body>
                </Accordion.Item>

                {/* <Accordion.Item eventKey="0">
                    <Accordion.Header></Accordion.Header>
                    <Accordion.Body>

                    </Accordion.Body>
                </Accordion.Item> */}
            </Accordion>
        </Container>
    );
}


export default Privacy;